debug:
  script:
    - ./gradlew clean testDebugUnitTest
  except:
    - /^v.*$/

bintray:
  script:
    - ./gradlew clean assembleRelease publishMavenAndroidPublicationToMavenLocal bintrayUpload
  only:
    - /^v.*$/