stages:
  - clean
  - build
  - publish
  - deploy

clean:
  stage: clean
  script:
    - ./gradlew clean

debug:
  stage: build
  script:
    - ./gradlew :compiler:assemble :compiler:test
    - ./gradlew :library:assembleDebug :library:testDebugUnitTest
  except:
    - tags

release:
  stage: build
  script:
    - ./gradlew :compiler:proguard
    - ./gradlew :library:assembleRelease
  artifacts:
    paths:
      - compiler/build
      - library/build
  except:
    - tags

mavenLocal:
  stage: publish
  script:
    - ./gradlew publishToMavenLocal
  except:
    - tags

bintray:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  when: manual