stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  script:
    - ./gradlew clean

bindings:
  stage: build
  script:
    - ./gradlew :bindings:proguard :bindings:test :bindings:publishToMavenLocal
  artifacts:
    paths:
      - bindings/build
  except:
    - tags

compiler:
  stage: build
  script:
    - ./gradlew :compiler:proguard :compiler:test :compiler:publishToMavenLocal
  dependencies:
    - bindings
  artifacts:
    paths:
      - compiler/build
  except:
    - tags

library_debug:
  stage: build
  script:
    - ./gradlew :library:assembleDebug :library:testDebugUnitTest
  dependencies:
    - compiler
  artifacts:
    paths:
      - library/build
  except:
    - tags

library_release:
  stage: build
  script:
    - ./gradlew :library:assembleRelease :library:publishToMavenLocal
  dependencies:
    - compiler
  artifacts:
    paths:
      - library/build
  except:
    - tags

bintray:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - library_release
  when: manual