stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  script:
    - ./gradlew clean

library_debug:
  stage: build
  script:
    - ./gradlew :bindings:proguard :bindings:test :bindings:publishToMavenLocal
    - ./gradlew :compiler:proguard :compiler:test :compiler:publishToMavenLocal
    - ./gradlew :library:assembleDebug :library:testDebugUnitTest
  except:
    - tags

library_release:
  stage: build
  script:
    - ./gradlew :library:assembleRelease :library:publishToMavenLocal
  except:
    - tags

bintray:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - library_release
  when: manual