stages:
  - clean
  - build
  - test
  - publish
  - deploy

cleanup:
  stage: clean
  script:
    - ./gradlew clean

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - library/build
  except:
    - tags

assembleRelease:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - library/build

unitTest:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  dependencies:
    - assembleDebug
  except:
    - tags

publishToMavenLocal:
  stage: publish
  script:
    - ./gradlew publishToMavenLocal
  artifacts:
    paths:
      - library/build
  dependencies:
    - assembleRelease

bintrayUpload:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - publishToMavenLocal
  when: manual
